name: Deploy to Staging

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

concurrency:
  group: staging_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: Build packages and apps
        run: npm run build
        env:
          PUBLIC_PATH: /craftbeerinternlnwza007
      - name: Deploy to Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
